{% set name = "label-studio-sdk" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
    sha256: 8ee436ed5c3a7bc283de68a5708e0438400fd7f5981ae0a516d44d0a77777302
  # todo: remove once 1.0.6 ships
  - url: https://raw.githubusercontent.com/HumanSignal/label-studio-sdk/refs/heads/master/LICENSE
    sha256: 972b33115efbe4fd8f2e6458ad4d9339067bf4f4b620f2224f24045d4d7c22f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - Pillow >=10.0.1
    - appdirs >=1.4.3
    - httpx >=0.21.2
    - ijson >=3.2.3
    - jsonschema =3.2.0
    - lxml >=4.2.5
    - nltk >=3.9.1
    - numpy <2.0.0
    - pandas >=0.24.0
    - pydantic >=1.9.2
    - requests >=2.22.0
    - requests-mock =1.12.1
    - typing_extensions >=4.0.0
    - ujson >=5.8.0
    - xmljson =0.2.1

test:
  imports:
    - label_studio_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/heartexlabs/label-studio-sdk
  summary: Label Studio annotation tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - CharalamposGeorgiadis
