{% set name = "label-studio-sdk" %}
{% set version = "0.0.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/label-studio-sdk-{{ version }}.tar.gz
  sha256: 86da9825d0cae27fa304f3ea0b12f573705ddc8ef21013cffc67dfa67970730e
  patches:
    - setup-py.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lxml >=4.2.5
    - requests >=2.22.0,<3
    - pydantic <3,>1.7
    - label-studio-tools >=0.0.1

test:
  imports:
    - label_studio_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/heartexlabs/label-studio-sdk
  summary: Label Studio annotation tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CharalamposGeorgiadis
