{% set name = "label-studio-sdk" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5fd7bf36f28576cb388dfc8eae2183bd1f3d25c308d12c02f0a2be8fc3a965a0
  patches:
    - setup-py.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - lxml >=4.2.5
    - requests >=2.22.0,<3
    - pydantic <3,>1.7
    - label-studio-tools >=0.0.1

test:
  imports:
    - label_studio_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/heartexlabs/label-studio-sdk
  summary: Label Studio annotation tool
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CharalamposGeorgiadis
