schema_version: 1

context:
  name: label-studio-sdk
  version: "2.0.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
    sha256: 374917ae7a4ee2037e1ecaffac077f9cb3d24f84ee4c00e505a63f50bd47c6c8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry
  run:
    - python >=${{ python_min }}
    - pillow >=11.3.0
    - appdirs >=1.4.3
    - datamodel-code-generator 0.26.1
    - httpx >=0.21.2
    - ijson >=3.2.3
    - jsf >=0.11.2,<0.12.0
    - jsonschema >=4.23.0
    - lxml >=4.2.5
    - nltk >=3.9.1,<4.0.0
    - numpy >=1.26.4,<3.0.0
    - opencv >=4.12.0,<5.0.0
    - pandas >=0.24.0
    - pydantic >=1.9.2
    - pydantic-core >=2.18.2,<3.0.0
    - pyjwt >=2.10.1,<3.0.0
    - requests >=2.22.0
    - requests-mock 1.12.1
    - typing_extensions >=4.0.0
    - ujson >=5.8.0
    - urllib3 >=2.5.0
    - xmljson 0.2.1
    - datamodel-code-generator ==0.26.1

tests:
  - python:
      imports:
        - label_studio_sdk
  - requirements:
      run:
        - python ${{ python_min }}
        - pip
    script:
      - pip check

about:
  summary: Label Studio annotation tool
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/heartexlabs/label-studio-sdk

extra:
  recipe-maintainers:
    - moritzwilksch
    - CharalamposGeorgiadis
